# Wahlkarten

```{r wahlkarten setup, echo=FALSE, message=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

suppressPackageStartupMessages(library(tidyverse)) # Tidying data
suppressPackageStartupMessages(library(sf)) # Reading Shapefiles
suppressPackageStartupMessages(library(here)) # Find correct place to load 
suppressPackageStartupMessages(library(tmap)) # Find correct place to load 

df <- readRDS(file=here("data/df_grune_pankow.rds")) %>% rename("Stimmanteil in %" = stimmanteil)

tmap_mode("view")

```

## EU-Wahl 2019
```{r}
df_grune_pankow <- df %>% filter(wahl == "EW_2019") 

tm_shape(df_grune_pankow) + 
  tm_fill("Stimmanteil in %", palette = "BuGn", alpha = .5) +
  tm_borders() +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = .5) +
  tm_layout(frame = FALSE) 
```

## Bundestagswahl Erststimme 2017
```{r}
df_grune_pankow <- df %>% filter(wahl == "BU1_2017") 

tm_shape(df_grune_pankow) + 
  tm_fill("Stimmanteil in %", palette = "BuGn", alpha = .5) +
  tm_borders() +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = .5) +
  tm_layout(frame = FALSE) 
```

## Bundestagswahl Zweitstimme 2017
```{r}
df_grune_pankow <- df %>% filter(wahl == "BU2_2017") 

tm_shape(df_grune_pankow) + 
  tm_fill("Stimmanteil in %", palette = "BuGn", alpha = .5) +
  tm_borders() +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = .5) +
  tm_layout(frame = FALSE) 
```

## BVV-Wahl 2016
```{r}
df_grune_pankow <- df %>% filter(wahl == "AGHBVV_2016") 

tm_shape(df_grune_pankow) + 
  tm_fill("Stimmanteil in %", palette = "BuGn", alpha = .5) +
  tm_borders() +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = .5) +
  tm_layout(frame = FALSE) 

```

## AGH Erststimme 2016
```{r}
df_grune_pankow <- df %>% filter(wahl == "AGHErststimme_2016") 

tm_shape(df_grune_pankow) + 
  tm_fill("Stimmanteil in %", palette = "BuGn", alpha = .5) +
  tm_borders() +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = .5) +
  tm_layout(frame = FALSE) 
```

## AGH Zweitstimme 2016
```{r}
df_grune_pankow <- df %>% filter(wahl == "AGHZweitstimme_2016") 

tm_shape(df_grune_pankow) + 
  tm_fill("Stimmanteil in %", palette = "BuGn", alpha = .5) +
  tm_borders() +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = .5) +
  tm_layout(frame = FALSE) 
```

## EU-Wahl 2014
```{r}
df_grune_pankow <- df %>% filter(wahl == "EU_2014") 

tm_shape(df_grune_pankow) + 
  tm_fill("Stimmanteil in %", palette = "BuGn", alpha = .5) +
  tm_borders() +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = .5) +
  tm_layout(frame = FALSE) 
```

## Bundestagswahl Erststimme 2013
```{r}
df_grune_pankow <- df %>% filter(wahl == "BUErststimme_2013") 

tm_shape(df_grune_pankow) + 
  tm_fill("Stimmanteil in %", palette = "BuGn", alpha = .5) +
  tm_borders() +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = .5) +
  tm_layout(frame = FALSE) 
```

## Bundestagswahl Zweitstimme 2013
```{r}
df_grune_pankow <- df %>% filter(wahl == "BUZweitstimme_2013") 

tm_shape(df_grune_pankow) + 
  tm_fill("Stimmanteil in %", palette = "BuGn", alpha = .5) +
  tm_borders() +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = .5) +
  tm_layout(frame = FALSE) 
```

## BVV-Wahl 2011
```{r}
df_grune_pankow <- df %>% filter(wahl == "AGHBVV_2011") 

tm_shape(df_grune_pankow) + 
  tm_fill("Stimmanteil in %", palette = "BuGn", alpha = .5) +
  tm_borders() +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = .5) +
  tm_layout(frame = FALSE) 

```

## AGH Erststimme 2011
```{r}
df_grune_pankow <- df %>% filter(wahl == "AGHErststimme_2011") 

tm_shape(df_grune_pankow) + 
  tm_fill("Stimmanteil in %", palette = "BuGn", alpha = .5) +
  tm_borders() +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = .5) +
  tm_layout(frame = FALSE) 
```

## AGH Zweitstimme 2011
```{r}
df_grune_pankow <- df %>% filter(wahl == "AGHZweitstimme_2011") 

tm_shape(df_grune_pankow) + 
  tm_fill("Stimmanteil in %", palette = "BuGn", alpha = .5) +
  tm_borders() +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = .5) +
  tm_layout(frame = FALSE) 
```

## EUwahl 2009
```{r}
df_grune_pankow <- df %>% filter(wahl == "EU_2009") 

tm_shape(df_grune_pankow) + 
  tm_fill("Stimmanteil in %", palette = "BuGn", alpha = .5) +
  tm_borders() +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = .5) +
  tm_layout(frame = FALSE) 
```


## Bundestagswahl Erststimme 2009
```{r}
df_grune_pankow <- df %>% filter(wahl == "BUErststimme_2009") 

tm_shape(df_grune_pankow) + 
  tm_fill("Stimmanteil in %", palette = "BuGn", alpha = .5) +
  tm_borders() +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = .5) +
  tm_layout(frame = FALSE) 
```

## Bundestagswahl Zweitstimme 2009
```{r}
df_grune_pankow <- df %>% filter(wahl == "BUZweitstimme_2009") 

tm_shape(df_grune_pankow) + 
  tm_fill("Stimmanteil in %", palette = "BuGn", alpha = .5) +
  tm_borders() +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = .5) +
  tm_layout(frame = FALSE) 
```
