# Zusammenhänge
```{r zusammenhaenge setup, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

suppressPackageStartupMessages(library(tidyverse)) # Tidying data
suppressPackageStartupMessages(library(sf)) # Reading Shapefiles
suppressPackageStartupMessages(library(here)) # Find correct place to load 
suppressPackageStartupMessages(library(tmap)) # Find correct place to load 

df_bu <- readRDS(file=here("data/df_bu.rds")) %>% filter(partei == "grune")
df_alter <- readRDS(file=here("data/df_alter.rds")) 
df_wohnqualitaet <- readRDS(file=here("data/df_wohnqualitaet.rds")) 

tmap_mode("view")

```

## Wie hängt das Alter mit den Wahlergebnissen der Grünen zusammen?
```{r zusammenhaenge1}
korrelationskoeffizent = df_bu %>% st_drop_geometry() %>% summarize(correlation = cor(stimmanteil, altersmittelwert)) %>% pull() %>% round(.,3) 

ggplot(df_bu, aes(x = altersmittelwert, y = stimmanteil)) +
  geom_jitter(aes(color = stimmanteil)) +
  scale_color_continuous(low = "lightgreen",  high = "darkgreen") +
  labs(x = "Altersmittelwert der Wahlbezirke", y = "Wahlergebnis in %") +  
  geom_smooth(method = "lm", se = TRUE) +
  theme_classic() +
  theme(legend.position = "none") +
  annotate("text", x = 52, y = 30, label = paste("Korrelations-Koeff:", korrelationskoeffizent)) + 
  theme(text = element_text(size = 20)) 
```

## Altesmittelwert der Wahlbezirke
```{r zusammenhaenge2}
tm_shape(df_alter) +
  tm_borders() +
  tm_fill("altersmittelwert", alpha = .5) +
    tm_layout(frame = FALSE) 
```

## Wie hängt die Wohnlage mit den Wahlergebnissen der Grünen zusammen?
### Gute Wohnlage
```{r zusammenhaenge3}
korrelationskoeffizent = df_wohnqualitaet %>% st_drop_geometry() %>% summarize(correlation = cor(stimmanteil, gutewohnlage, use = "complete.obs")) %>% pull() %>% round(.,2)

ggplot(df_wohnqualitaet, aes(x = gutewohnlage, y = stimmanteil)) +
  geom_jitter(aes(color = stimmanteil)) +
  scale_color_continuous(low = "lightgreen",  high = "darkgreen") +
  labs(x = "Anteil gute Wohnlage pro Wahlbezirk", y = "Wahlergebnis der Grünen in %") +  
  geom_smooth(method = "lm", se = TRUE) +
  theme_classic() +
  theme(legend.position = "none") + 
  annotate("text", x = 70, y = 70, label = paste("Korrelations-Koeff:", korrelationskoeffizent)) +
  theme(text = element_text(size = 20)) 

```

### Einfache Wohnlage
```{r}
korrelationskoeffizent = df_wohnqualitaet %>% st_drop_geometry() %>% summarize(correlation = cor(stimmanteil, einfachewohnlage, use = "complete.obs")) %>% pull() %>% round(.,2) 

ggplot(df_wohnqualitaet, aes(x = einfachewohnlage, y = stimmanteil)) +
  geom_jitter(aes(color = stimmanteil)) +
  scale_color_continuous(low = "lightgreen",  high = "darkgreen") +
  labs(x = "Anteil einfache Wohnlage pro Wahlbezirk", y = "Wahlergebnis der Grünen in %") +  
  geom_smooth(method = "lm", se = TRUE) +
  theme_classic() +
  theme(legend.position = "none") + 
  annotate("text", x = 70, y = 70, label = paste("Korrelations-Koeff:", korrelationskoeffizent)) +
  theme(text = element_text(size = 20)) 

```

## Wie hängt Lärm und das Wahlergebnis der Grünen zusammen?
```{r zusammenhaenge6}
korrelationskoeffizent = df_wohnqualitaet %>% st_drop_geometry() %>% summarize(correlation = cor(stimmanteil, lärmanteil, use = "complete.obs")) %>% pull() %>% round(.,3) 

ggplot(df_wohnqualitaet, aes(x = lärmanteil, y = stimmanteil)) +
  geom_jitter(aes(color = stimmanteil)) +
  scale_color_continuous(low = "lightgreen",  high = "darkgreen") +
  labs(x = "Anteil der Wohnlagen mit Lärm pro Wahlbezirk", y = "Wahlergebnis der Grünen in %") +  
  geom_smooth(method = "lm", se = TRUE) +
  annotate("text", x = 70, y = 70, label = paste("Korrelations-Koeff:", korrelationskoeffizent)) +
  theme_classic() +
  theme(legend.position = "none") 
```

## Anteil der Wohnlagen mit Lärm pro Wahlbezirk als Karte
```{r zusammenhaenge7}
tm_shape(df_wohnqualitaet) +
  tm_borders() +
  tm_fill("lärmanteil", alpha = .5) +
    tm_layout(frame = FALSE) 
```
